// Search over the hosted symbol catalog (§5.7 picker). The indexes are
// generated by scripts/symbols/build-symbol-index.mjs and served as static
// assets — they grow automatically with the full library run and are cached
// offline by the service worker.
//
// ONE INDEX PER LANGUAGE (§19.7). ARASAAC's pictograms are language-neutral
// images but their keywords are not, and the picker used to search English
// only: a Spanish, Polish or Brazilian caregiver had to guess the English
// word to find a symbol for a board authored in their own language. Only the
// profile's language is fetched, the way the prediction lexicon is.
import { getSymbolUri } from './SymbolService'

export interface SymbolEntry {
  id: string // namespaced ref, e.g. 'arasaac:2788'
  library: string
  keywords: string[]
}

export interface SymbolResult {
  id: string
  label: string
  uri: string
}

/** Keywords folded once at load, so a keystroke never re-normalizes 13k strings. */
interface IndexedEntry extends SymbolEntry {
  folded: string[]
}

const BASE = process.env.EXPO_PUBLIC_BASE_URL ?? ''
const FALLBACK_LANG = 'en'

const caches = new Map<string, IndexedEntry[]>()
const inFlight = new Map<string, Promise<IndexedEntry[]>>()

function langCode(language: string | undefined): string {
  return (language ?? FALLBACK_LANG).slice(0, 2).toLowerCase()
}

/**
 * Case- and accent-insensitive form for matching. Someone typing on a
 * keyboard without the right dead keys — or in a hurry — should still find
 * `água` by typing `agua` and `jeść` by typing `jesc`. NFD decomposition
 * handles the accented vowels; Polish `ł` has no decomposition, so it is
 * mapped by hand.
 */
export function fold(value: string): string {
  return value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/ł/g, 'l')
}

function index(entries: SymbolEntry[]): IndexedEntry[] {
  return entries.map((entry) => ({ ...entry, folded: entry.keywords.map(fold) }))
}

async function fetchIndex(code: string): Promise<IndexedEntry[]> {
  try {
    const response = await fetch(`${BASE}/symbolIndex/${code}.json`)
    return response.ok ? index(await response.json()) : []
  } catch {
    return [] // native (Phase 2) loads from the bundled zip instead
  }
}

async function loadIndex(language: string | undefined): Promise<IndexedEntry[]> {
  const code = langCode(language)
  const cached = caches.get(code)
  if (cached) return cached
  const pending = inFlight.get(code)
  if (pending) return pending

  const load = (async () => {
    let entries = await fetchIndex(code)
    // A deploy that shipped only the English index must not leave the picker
    // empty — an English catalog is degraded, an empty one is broken.
    if (!entries.length && code !== FALLBACK_LANG) {
      entries = caches.get(FALLBACK_LANG) ?? (await fetchIndex(FALLBACK_LANG))
    }
    caches.set(code, entries)
    inFlight.delete(code)
    return entries
  })()

  inFlight.set(code, load)
  return load
}

export async function searchSymbols(
  query: string,
  language?: string,
  limit = 30,
): Promise<SymbolResult[]> {
  const needle = fold(query.trim())
  if (!needle) return []
  const entries = await loadIndex(language)

  // exact keyword matches first, then prefix, then substring
  const scored: Array<[number, IndexedEntry]> = []
  for (const entry of entries) {
    let best = 0
    for (const keyword of entry.folded) {
      if (keyword === needle) best = Math.max(best, 3)
      else if (keyword.startsWith(needle)) best = Math.max(best, 2)
      else if (keyword.includes(needle)) best = Math.max(best, 1)
    }
    if (best > 0) scored.push([best, entry])
  }
  scored.sort((a, b) => b[0] - a[0])

  return scored.slice(0, limit).flatMap(([, entry]) => {
    const uri = getSymbolUri(entry.id)
    return uri ? [{ id: entry.id, label: entry.keywords[0] ?? entry.id, uri }] : []
  })
}
