// Search over the hosted symbol catalog (§5.7 picker). The index is
// generated by scripts/symbols/build-symbol-index.mjs and served as a
// static asset — it grows automatically with the full library run and
// is cached offline by the service worker.
import { getSymbolUri } from './SymbolService'

export interface SymbolEntry {
  id: string // namespaced ref, e.g. 'arasaac:2788'
  library: string
  keywords: string[]
}

export interface SymbolResult {
  id: string
  label: string
  uri: string
}

const BASE = process.env.EXPO_PUBLIC_BASE_URL ?? ''
let indexCache: SymbolEntry[] | null = null

async function loadIndex(): Promise<SymbolEntry[]> {
  if (indexCache) return indexCache
  try {
    const response = await fetch(`${BASE}/symbolIndex.json`)
    indexCache = response.ok ? await response.json() : []
  } catch {
    indexCache = [] // native (Phase 2) loads from the bundled zip instead
  }
  return indexCache!
}

export async function searchSymbols(query: string, limit = 30): Promise<SymbolResult[]> {
  const needle = query.trim().toLowerCase()
  if (!needle) return []
  const index = await loadIndex()

  // exact keyword matches first, then prefix, then substring
  const scored: Array<[number, SymbolEntry]> = []
  for (const entry of index) {
    let best = 0
    for (const keyword of entry.keywords) {
      const k = keyword.toLowerCase()
      if (k === needle) best = Math.max(best, 3)
      else if (k.startsWith(needle)) best = Math.max(best, 2)
      else if (k.includes(needle)) best = Math.max(best, 1)
    }
    if (best > 0) scored.push([best, entry])
  }
  scored.sort((a, b) => b[0] - a[0])

  return scored.slice(0, limit).flatMap(([, entry]) => {
    const uri = getSymbolUri(entry.id)
    return uri ? [{ id: entry.id, label: entry.keywords[0] ?? entry.id, uri }] : []
  })
}
