import { POS_COLORS, PartOfSpeech, UI_COLORS } from '../constants/colors'
import type { Storage } from '../storage/types'
import type { Button, ButtonAction, Page, PageSet } from '../types/models'
import { uuid } from '../utils/uuid'

// Seeds the bundled Core Vocabulary page set per §19: a 5×6 grid where
// columns 0–2 are the persistent core region — identical words at
// identical positions on EVERY page (§19.5 acceptance criterion) — and
// columns 3–5 hold page-specific content: topic-navigation buttons on
// the home page, topic words on topic pages.
//
// Word lists are the §19.3 candidate set, pending SLP validation.
// TODO(§19.5): replace with SLP-reviewed .obf content before v1.0.

type Word = [string, PartOfSpeech]

// §19.3 word lists live in coreWords.json (shared with the symbol
// pipeline scripts); seedSymbolMap.json is generated by
// scripts/symbols/build-seed-symbols.mjs
import coreWordsJson from './coreWords.json'
import seedSymbolMapJson from './seedSymbolMap.json'

// JSON imports type as string[][] — the file's shape is validated by the
// pipeline scripts that share it
const CORE_WORDS = coreWordsJson.core as unknown as Word[]
const TOPICS = coreWordsJson.topics as unknown as Record<string, Word[]>
const SYMBOL_MAP = seedSymbolMapJson as Record<string, string>

const ROWS = 5
const COLUMNS = 6

function makeButton(
  pageId: string,
  label: string,
  pos: PartOfSpeech,
  row: number,
  column: number,
  actions: ButtonAction[],
  isNavigationButton = false,
  now = 0,
): Button {
  return {
    id: uuid(),
    pageId,
    row,
    column,
    rowSpan: 1,
    columnSpan: 1,
    label,
    symbolId: SYMBOL_MAP[label],
    backgroundColor: POS_COLORS[pos],
    borderColor: UI_COLORS.buttonBorder,
    borderWidth: 1,
    labelColor: UI_COLORS.label,
    labelFontSize: 14,
    labelFontWeight: 'bold',
    symbolScale: 0.65,
    isHidden: false,
    isNavigationButton,
    actions,
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  }
}

// Places `words` row-major into columns [columnOffset, columnOffset+2]
function placeWords(
  pageId: string,
  words: Word[],
  columnOffset: number,
  actionsFor: (label: string) => ButtonAction[],
  now: number,
): Button[] {
  return words.map(([label, pos], i) =>
    makeButton(
      pageId,
      label,
      pos,
      Math.floor(i / 3),
      columnOffset + (i % 3),
      actionsFor(label),
      false,
      now,
    ),
  )
}

// §19.4 Quick Phrases — 18 one-tap complete utterances, 3×6 single page
const QUICK_PHRASES: Array<[string, PartOfSpeech]> = [
  ['Hello!', 'social'],
  ['Goodbye!', 'social'],
  ['How are you?', 'question'],
  ['Thank you!', 'social'],
  ['Please!', 'social'],
  ['I like that!', 'social'],
  ['I need help.', 'little'],
  ['I need a break.', 'little'],
  ['Can I have more?', 'question'],
  ['I need the bathroom.', 'little'],
  ["That's funny!", 'social'],
  ["That's great!", 'social'],
  ["I don't like that.", 'descriptor'],
  ['Look at this!', 'social'],
  ["That's not what I meant.", 'descriptor'],
  ['Something else.', 'descriptor'],
  ['Come here please!', 'social'],
  ['Something is wrong!', 'question'],
]

const SEED_META_KEY = 'coreVocabularySeeded'
const SEED_VERSION_KEY = 'seedVersion'
// Bump when seed content changes — pre-release only, wipes local data.
// Post-release this becomes a proper migration.
const SEED_VERSION = '3'

export async function seedIfNeeded(storage: Storage): Promise<string> {
  const existing = await storage.getMeta(SEED_META_KEY)
  const version = await storage.getMeta(SEED_VERSION_KEY)
  if (existing && version === SEED_VERSION) return existing // value = pageSetId
  if (existing) await storage.clearAll()

  const now = Date.now()
  const pageSetId = uuid()
  const homePageId = uuid()
  const topicPageIds = new Map(Object.keys(TOPICS).map((t) => [t, uuid()]))

  const pageSet: PageSet = {
    id: pageSetId,
    name: 'Core Vocabulary',
    description: 'Bundled starter vocabulary (§19) — pending SLP review',
    language: 'en',
    rootPageId: homePageId,
    schemaVersion: 1,
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  }

  const makePage = (id: string, name: string): Page => ({
    id,
    pageSetId,
    name,
    rows: ROWS,
    columns: COLUMNS,
    backgroundColor: '#FFFFFF',
    showMessageBar: true,
    showToolbar: true,
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  })

  const appendAction = (): ButtonAction[] => [{ type: 'append_to_message' }]

  const pages: Page[] = [makePage(homePageId, 'Home')]
  const buttons: Button[] = []

  // Core region — identical on every page (home + topics)
  const allPageIds = [homePageId, ...topicPageIds.values()]
  for (const pageId of allPageIds) {
    buttons.push(...placeWords(pageId, CORE_WORDS, 0, appendAction, now))
  }

  // Home page right side: topic-navigation buttons
  let navIndex = 0
  for (const [topic, pageId] of topicPageIds) {
    buttons.push(
      makeButton(
        homePageId,
        topic,
        'category',
        Math.floor(navIndex / 3),
        3 + (navIndex % 3),
        [{ type: 'navigate', pageId }],
        true,
        now,
      ),
    )
    navIndex++
  }

  // Topic pages: right side holds the topic words
  for (const [topic, words] of Object.entries(TOPICS)) {
    const pageId = topicPageIds.get(topic)!
    pages.push(makePage(pageId, topic))
    buttons.push(...placeWords(pageId, words, 3, appendAction, now))
  }

  await storage.createPageSet(pageSet)
  for (const page of pages) await storage.createPage(page)
  for (const button of buttons) await storage.createButton(button)

  await seedQuickPhrases(storage, now)

  await storage.setMeta(SEED_META_KEY, pageSetId)
  await storage.setMeta(SEED_VERSION_KEY, SEED_VERSION)

  return pageSetId
}

// §19.4: each button speaks its full sentence in one tap, bypassing the
// message bar
async function seedQuickPhrases(storage: Storage, now: number): Promise<void> {
  const pageSetId = uuid()
  const pageId = uuid()

  await storage.createPageSet({
    id: pageSetId,
    name: 'Quick Phrases',
    description: 'Pre-stored phrases spoken with one tap (§19.4)',
    language: 'en',
    rootPageId: pageId,
    schemaVersion: 1,
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  })

  await storage.createPage({
    id: pageId,
    pageSetId,
    name: 'Quick Phrases',
    rows: 3,
    columns: 6,
    backgroundColor: '#FFFFFF',
    showMessageBar: true,
    showToolbar: true,
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  })

  for (let i = 0; i < QUICK_PHRASES.length; i++) {
    const [label, pos] = QUICK_PHRASES[i]
    await storage.createButton(
      makeButton(
        pageId,
        label,
        pos,
        Math.floor(i / 6),
        i % 6,
        [{ type: 'speak_label' }],
        false,
        now,
      ),
    )
  }
}
