import { POS_COLORS, PartOfSpeech, UI_COLORS } from '../constants/colors'
import type { Storage } from '../storage/types'
import type { Button, ButtonAction, Page, PageSet } from '../types/models'

// Built-in content uses STABLE, deterministic ids (not random uuids) so
// content updates can rebuild the bundled pages/buttons IN PLACE while
// leaving user profiles, word lists, tracking, and user-created pages
// untouched. Profile.activePageSetId and word-list button references stay
// valid across versions because the ids never change.
const CORE_SET_ID = 'builtin-core-vocabulary'
const QUICK_SET_ID = 'builtin-quick-phrases'
const CORE_HOME_ID = 'builtin-core-home'
const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-')
const topicPageId = (topic: string) => `builtin-core-${slug(topic)}`

// Seeds the bundled Core Vocabulary page set per §19: a 5×6 grid where
// columns 0–2 are the persistent core region — identical words at
// identical positions on EVERY page (§19.5 acceptance criterion) — and
// columns 3–5 hold page-specific content: topic-navigation buttons on
// the home page, topic words on topic pages.
//
// Word lists are the §19.3 candidate set, pending SLP validation.
// TODO(§19.5): replace with SLP-reviewed .obf content before v1.0.

type Word = [string, PartOfSpeech]

// §19.3 word lists live in coreWords.json (shared with the symbol
// pipeline scripts); seedSymbolMap.json is generated by
// scripts/symbols/build-seed-symbols.mjs
import coreWordsJson from './coreWords.json'
import seedSymbolMapJson from './seedSymbolMap.json'

// JSON imports type as string[][] — the file's shape is validated by the
// pipeline scripts that share it
const CORE_WORDS = coreWordsJson.core as unknown as Word[]
const TOPICS = coreWordsJson.topics as unknown as Record<string, Word[]>
const SYMBOL_MAP = seedSymbolMapJson as Record<string, string>

const ROWS = 5
const COLUMNS = 6

function makeButton(
  pageId: string,
  label: string,
  pos: PartOfSpeech,
  row: number,
  column: number,
  actions: ButtonAction[],
  isNavigationButton = false,
  now = 0,
): Button {
  return {
    id: `${pageId}-r${row}-c${column}`, // stable: one button per cell
    pageId,
    row,
    column,
    rowSpan: 1,
    columnSpan: 1,
    label,
    symbolId: SYMBOL_MAP[label],
    backgroundColor: POS_COLORS[pos],
    borderColor: UI_COLORS.buttonBorder,
    borderWidth: 1,
    labelColor: UI_COLORS.label,
    labelFontSize: 14,
    labelFontWeight: 'bold',
    symbolScale: 0.65,
    isHidden: false,
    isNavigationButton,
    actions,
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  }
}

// Places `words` row-major into columns [columnOffset, columnOffset+2].
// `startIndex` shifts placement forward (used to reserve the first content
// cell for a Back button); words that overflow past the grid flow off.
function placeWords(
  pageId: string,
  words: Word[],
  columnOffset: number,
  actionsFor: (label: string) => ButtonAction[],
  now: number,
  startIndex = 0,
): Button[] {
  return words
    .map(([label, pos], i) => {
      const idx = i + startIndex
      return makeButton(
        pageId,
        label,
        pos,
        Math.floor(idx / 3),
        columnOffset + (idx % 3),
        actionsFor(label),
        false,
        now,
      )
    })
    .filter((b) => b.row < ROWS)
}

// A real Back button occupying the first content cell (§19.5 motor plan:
// its position is fixed in the data, so it never moves between edit and
// use mode). SymbolButton draws a ← arrow for navigate_back buttons.
function makeBackButton(pageId: string, now: number): Button {
  return {
    ...makeButton(pageId, 'Back', 'category', 0, 3, [{ type: 'navigate_back' }], false, now),
    backgroundColor: '#ECEFF1',
    symbolId: undefined,
  }
}

// §19.4 Quick Phrases — 18 one-tap complete utterances, 3×6 single page
const QUICK_PHRASES: Array<[string, PartOfSpeech]> = [
  ['Hello!', 'social'],
  ['Goodbye!', 'social'],
  ['How are you?', 'question'],
  ['Thank you!', 'social'],
  ['Please!', 'social'],
  ['I like that!', 'social'],
  ['I need help.', 'little'],
  ['I need a break.', 'little'],
  ['Can I have more?', 'question'],
  ['I need the bathroom.', 'little'],
  ["That's funny!", 'social'],
  ["That's great!", 'social'],
  ["I don't like that.", 'descriptor'],
  ['Look at this!', 'social'],
  ["That's not what I meant.", 'descriptor'],
  ['Something else.', 'descriptor'],
  ['Come here please!', 'social'],
  ['Something is wrong!', 'question'],
]

const SEED_META_KEY = 'coreVocabularySeeded'
const SEED_VERSION_KEY = 'seedVersion'
// Bump when bundled content changes. From v6 on, a bump runs a
// data-preserving migration (rebuildBuiltInContent) — NOT a wipe.
const SEED_VERSION = '7'

export async function seedIfNeeded(storage: Storage): Promise<string> {
  const existing = await storage.getMeta(SEED_META_KEY)
  const version = await storage.getMeta(SEED_VERSION_KEY)
  if (existing === CORE_SET_ID && version === SEED_VERSION) return CORE_SET_ID

  if (existing && existing !== CORE_SET_ID) {
    // Pre-stable-id install (random uuids from ≤ v5) → one final clean
    // reset to adopt stable ids. This is the last wipe; there are no
    // real users yet, and every future update is gentle.
    await storage.clearAll()
    await createBuiltInSets(storage)
  } else if (existing) {
    // Stable-id install, content changed → migrate in place, keeping
    // profiles, word lists, tracking, and user-created pages.
    await rebuildBuiltInContent(storage)
  } else {
    await createBuiltInSets(storage) // first run
  }

  await storage.setMeta(SEED_VERSION_KEY, SEED_VERSION)
  return CORE_SET_ID
}

// Migration + "restore defaults" safety net. Rebuilds ONLY the built-in
// pages/buttons (isBuiltIn) from the current seed, leaving user-created
// pages (isBuiltIn=false), profiles, word lists, and tracking intact.
// Because built-in ids are stable, links and references survive.
export async function rebuildBuiltInContent(storage: Storage): Promise<string> {
  for (const set of (await storage.getPageSets()).filter((s) => s.isBuiltIn)) {
    for (const page of await storage.getPagesForPageSet(set.id)) {
      if (page.isBuiltIn) await storage.deletePage(page.id) // keep user pages
    }
  }

  await createBuiltInSets(storage) // upserts set rows + built-in pages/buttons

  // Defensive: if a profile pointed at a set that no longer exists,
  // send it to Core (shouldn't happen with stable ids).
  const ids = new Set((await storage.getPageSets()).map((s) => s.id))
  for (const user of await storage.getUsers()) {
    if (!ids.has(user.activePageSetId)) {
      await storage.updateUser({ ...user, activePageSetId: CORE_SET_ID, updatedAt: Date.now() })
    }
  }

  return CORE_SET_ID
}

// Back-compat alias — Settings still calls this name for "restore".
export const restoreBuiltInPageSets = rebuildBuiltInContent

async function createBuiltInSets(storage: Storage): Promise<string> {
  const now = Date.now()
  const pageSetId = CORE_SET_ID
  const homePageId = CORE_HOME_ID
  const topicPageIds = new Map(Object.keys(TOPICS).map((t) => [t, topicPageId(t)]))

  const pageSet: PageSet = {
    id: pageSetId,
    name: 'Core Vocabulary',
    description: 'Bundled starter vocabulary (§19) — pending SLP review',
    language: 'en',
    rootPageId: homePageId,
    schemaVersion: 1,
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  }

  const makePage = (id: string, name: string): Page => ({
    id,
    pageSetId,
    name,
    rows: ROWS,
    columns: COLUMNS,
    backgroundColor: '#FFFFFF',
    showMessageBar: true,
    showToolbar: true,
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  })

  const appendAction = (): ButtonAction[] => [{ type: 'append_to_message' }]

  const pages: Page[] = [makePage(homePageId, 'Home')]
  const buttons: Button[] = []

  // Core region — identical on every page (home + topics)
  const allPageIds = [homePageId, ...topicPageIds.values()]
  for (const pageId of allPageIds) {
    buttons.push(...placeWords(pageId, CORE_WORDS, 0, appendAction, now))
  }

  // Home page right side: topic-navigation buttons
  let navIndex = 0
  for (const [topic, pageId] of topicPageIds) {
    buttons.push(
      makeButton(
        homePageId,
        topic,
        'category',
        Math.floor(navIndex / 3),
        3 + (navIndex % 3),
        [{ type: 'navigate', pageId }],
        true,
        now,
      ),
    )
    navIndex++
  }

  // Topic pages: Back button in the first content cell, then topic words
  // flow in after it — a fixed layout identical in edit and use mode.
  for (const [topic, words] of Object.entries(TOPICS)) {
    const pageId = topicPageIds.get(topic)!
    pages.push(makePage(pageId, topic))
    buttons.push(makeBackButton(pageId, now))
    buttons.push(...placeWords(pageId, words, 3, appendAction, now, 1))
  }

  await storage.createPageSet(pageSet)
  for (const page of pages) await storage.createPage(page)
  for (const button of buttons) await storage.createButton(button)

  await seedQuickPhrases(storage, now)

  await storage.setMeta(SEED_META_KEY, CORE_SET_ID)

  return pageSetId
}

// §19.4: each button speaks its full sentence in one tap, bypassing the
// message bar
async function seedQuickPhrases(storage: Storage, now: number): Promise<void> {
  const pageSetId = QUICK_SET_ID
  const pageId = `${QUICK_SET_ID}-page`
  await storage.setMeta('quickPhrasesPageSetId', pageSetId) // toolbar jump

  await storage.createPageSet({
    id: pageSetId,
    name: 'Quick Phrases',
    description: 'Pre-stored phrases spoken with one tap (§19.4)',
    language: 'en',
    rootPageId: pageId,
    schemaVersion: 1,
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  })

  await storage.createPage({
    id: pageId,
    pageSetId,
    name: 'Quick Phrases',
    rows: 3,
    columns: 6,
    backgroundColor: '#FFFFFF',
    showMessageBar: true,
    showToolbar: true,
    isBuiltIn: true,
    createdAt: now,
    updatedAt: now,
  })

  for (let i = 0; i < QUICK_PHRASES.length; i++) {
    const [label, pos] = QUICK_PHRASES[i]
    await storage.createButton(
      makeButton(
        pageId,
        label,
        pos,
        Math.floor(i / 6),
        i % 6,
        [{ type: 'speak_label' }],
        false,
        now,
      ),
    )
  }
}
